# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 5 SDK'
  inputs:
    packageType: 'sdk'
    version: '5.x'
    
- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    projects: 'SomeSolution.sln'
    feedsToUse: 'config'
    nugetConfigPath: '.nuget/NuGet.config'

- task: DotNetCoreCLI@2
  displayName: 'Publish to Azure'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'SomeProjectFolder/SomeWebProject.csproj'
    arguments: '/p:PublishProfile=profile-name /p:Password=$(WebDeployPassword)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
